### ISSUE TITLE
what filetypes can the cli be used on?

### ISSUE THREAD

**Issue by tooptoop4** [mxmlnkn/rapidgzip#42]
the docs seem to imply gzip files are handled but in https://github.com/mxmlnkn/rapidgzip/releases/tag/rapidgzip-v0.14.0 it mentioned bzip2 is supported too? can u confirm

**Comment by mxmlnkn** [comment]
Yes. First-class support is gzip. But while trying to generalize the architecture to be able to handle LZ4, I added support for other formats. In total, rapidgzip now supports:

 - gzip
 - zlib
 - raw deflate
 - bzip2

Bzip2 decompression may be slightly slower than the original ibzip2 though because of the chunk finder and larger chunk size.
